"""add stakeholder model

Revision ID: 017_add_stakeholder_model
Revises: 31de748cb282_add_integration_fields
Create Date: 2026-02-12 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '017_add_stakeholder_model'
down_revision = '31de748cb282_add_integration_fields'  # Linking to the latest numeric migration? No, linking to the latest alphabetical one which seems to be 31de... wait.
# The list has numeric prefixes but also hashes. '31de...' seems to be the latest based on the list.
# 016_remove_treatment_strategy.py
# 31de748cb282_add_integration_fields.py
# ffaebe663715_enable_rls.py

# Based on file timestamps or naming convention, it's hard to be 100% sure which is "head" without running alembic heads.
# However, usually the hash ones are generated by alembic. 
# Let's target the one that seems most recent. 
# "ffaebe663715_enable_rls.py" might be the latest if it was generated after "31de...".
# But "31de..." is "add_integration_fields". 
# Let's assume "ffaebe663715_enable_rls.py" is the latest given RLS is usually a late addition.
# Actually, looking at the list, they are not sorted by time.
# "ffaebe663715" and "31de748cb282" don't have prefixes.
# I'll guess "ffaebe663715_enable_rls.py" is the latest.

down_revision = 'ffaebe663715' 
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relevance_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stakeholder_tenant_id'), 'stakeholder', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stakeholder_tenant_id'), table_name='stakeholder')
    op.drop_table('stakeholder')
    # ### end Alembic commands ###
